---
- name: Install Symphony
  hosts: 127.0.0.1
  connection: local
  vars:
    # Default values
    cluster_name: cluster1
    host_factory:
      api_endpoint: hpc-cluster.cloud.ibm.com/api/v1

  pre_tasks:
    - set_fact:
        compute_node: "Y"
      tags: compute

    - set_fact:
        compute_node: "N"
      tags: ['master', 'failover']

  roles:
    - role: common
      tags: always
    - role: management
      tags: ['master', 'failover']
    - role: compute
      tags: compute


- name: Configure master
  hosts: 127.0.0.1
  connection: local
  tags: master

  pre_tasks:
    - shell: ". /opt/ibm/spectrumcomputing/profile.platform; egoconfig join {{ ansible_fqdn }} -f; egoconfig setentitlement /tmp/symphony-entitlement"
      become: true
      become_user: egoadmin

    - shell: ". /opt/ibm/spectrumcomputing/profile.platform; egoconfig mghost /failover -f"
      become: true
      become_user: egoadmin

    - file:
        path: /failover/configured-{{ ansible_hostname }}
        owner: root
        group: root
        mode: 0644
        state: touch

    - wait_for:
        path: /failover/configured-{{ mgmt2.hostname }}
        sleep: 5
        timeout: 3600

    - shell: su egoadmin -c ". /opt/ibm/spectrumcomputing/profile.platform; egoconfig masterlist {{ ansible_hostname }},{{ mgmt2.hostname }} -f"

  roles:
    - hostfactory


- name: Configure failover
  hosts: 127.0.0.1
  connection: local
  tags: failover

  pre_tasks:
    - wait_for:
        path: /failover/configured-{{ mgmt1.hostname }}
        sleep: 5
        timeout: 3600

    - shell: ". /opt/ibm/spectrumcomputing/profile.platform; egoconfig join {{ ansible_fqdn }} -f"
      become: true
      become_user: egoadmin

    - shell: ". /opt/ibm/spectrumcomputing/profile.platform; egoconfig mghost /failover -f"
      become: true
      become_user: egoadmin

    - file:
        path: /failover/configured-{{ ansible_hostname }}
        owner: root
        group: root
        mode: 0644
        state: touch

  roles:
    - hostfactory


- name: Configure compute
  hosts: 127.0.0.1
  connection: local
  tags: compute

  tasks:
    - shell: ". /opt/ibm/spectrumcomputing/profile.platform; egoconfig join {{ mgmt1.hostname }} -f"
      become: true
      become_user: egoadmin


- name: Configure/start ego service (all nodes)
  hosts: 127.0.0.1
  connection: local
  tags: always

  tasks:
    - shell: . /opt/ibm/spectrumcomputing/profile.platform; egosetrc.sh

    - shell: . /opt/ibm/spectrumcomputing/profile.platform; egosetsudoers.sh -f

    - copy:
        dest: /etc/profile.d/spectrumcomputing.sh
        content: |
          [ -f /opt/ibm/spectrumcomputing/profile.platform ] && source /opt/ibm/spectrumcomputing/profile.platform
          [ -f /opt/lsf/conf/profile.lsf ] && source /opt/lsf/conf/profile.lsf
        owner: root
        group: root
        mode: 0755

    - service:
        name: ego
        state: started
