---

- name: Get Kernel Version
  shell: uname -r
  register: kernel_version

- name: Check modules directory
  stat:
    path: "/lib/modules/{{ kernel_version.stdout }}"
  register: modules_dir

- name: Update kernel for CentOS and RedHat
  yum:
    name: "kernel-{{ kernel_version.stdout }}"
    state: present
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and
        (not modules_dir.stat.exists)

- name: Load NFS module
  modprobe:
    name: nfs
    state: present

- stat:
    path: /etc/cloud/cloud.cfg
  register: cloud_config

- replace:
    path: "/etc/cloud/cloud.cfg"
    regexp: "(.*)update_etc_hosts"
    replace: "#\\1update_etc_hosts"
  when: cloud_config.stat.exists

- user:
    name: egoadmin
    shell: /bin/bash
    home: /home/egoadmin
    createhome: yes

- copy:
    dest: /etc/security/limits.d/30-egoadmin.conf
    content: |
      egoadmin soft nproc 65536
      egoadmin hard nproc 65536
      egoadmin soft nofile 65536
      egoadmin hard nofile 65536
    mode: 0644
    owner: root
    group: root

- file:
    path: /root/.aws
    state: directory
    owner: root
    group: root
    mode: 0700

- copy:
    dest: /root/.aws/credentials
    content: |
      [default]
      aws_access_key_id = {{ cos.access_key_id }}
      aws_secret_access_key = {{ cos.secret_access_key }}
    mode: 0600
    owner: root
    group: root

- copy:
    dest: /root/.aws/config
    content: |
      [default]
    mode: 0600
    owner: root
    group: root

- stat:
    path: /opt/ibm/spectrumcomputing/
  register: installdir

- shell: aws --endpoint=https://s3.private.us.cloud-object-storage.appdomain.cloud s3 cp s3://{{ cos.install_bucket }}/{{ item }} .
  with_items:
    - sym-7.2.1.0_x86_64.bin
    - sym-7.2.1.1_x86_64.tar.gz
    - sym721ent
  args:
    chdir: /tmp
  when: not installdir.stat.exists

- file:
    path: /tmp/sym-7.2.1.0_x86_64.bin
    mode: 0755
  when: not installdir.stat.exists

- shell: IBM_SPECTRUM_SYMPHONY_LICENSE_ACCEPT=Y EGOCOMPUTEHOST={{ compute_node }} CLUSTERNAME={{ cluster_name }} /tmp/sym-7.2.1.0_x86_64.bin --quiet
  args:
    creates: /opt/ibm/spectrumcomputing

- shell: . /opt/ibm/spectrumcomputing/profile.platform; egosh -V | grep 7.2.1.1 >/dev/null 2>&1
  failed_when: false
  register: patched

- unarchive:
    src: /tmp/sym-7.2.1.1_x86_64.tar.gz
    dest: /tmp
    remote_src: yes
  when: patched.rc != 0

- shell: . /opt/ibm/spectrumcomputing/profile.platform && /tmp/sym-7.2.1.1.sh
  args:
    chdir: /tmp
  when: patched.rc != 0
