---

- set_fact:
    accept_symphony_license: "N"

- set_fact:
    accept_symphony_license: "Y"
  when: IBM_spectrum_symphony.accept_license

- stat:
    path: /etc/cloud/cloud.cfg
  register: cloud_config

- replace:
    path: "/etc/cloud/cloud.cfg"
    regexp: "(.*)update_etc_hosts"
    replace: "#\\1update_etc_hosts"
  when: cloud_config.stat.exists

- user:
    name: egoadmin
    shell: /bin/bash
    home: /home/egoadmin
    createhome: yes

- copy:
    dest: /etc/security/limits.d/30-egoadmin.conf
    content: |
      egoadmin soft nproc 65536
      egoadmin hard nproc 65536
      egoadmin soft nofile 65536
      egoadmin hard nofile 65536
    mode: 0644
    owner: root
    group: root

- file:
    path: /root/.aws
    state: directory
    owner: root
    group: root
    mode: 0700

- stat:
    path: /opt/ibm/spectrumcomputing/
  register: installdir

- get_url:
    url: "https://s3.private.us.cloud-object-storage.appdomain.cloud/hpc-install-symphony/{{ item.name }}"
    dest: "/tmp/{{ item.dest }}"
  with_items:
    - { "name": "sym-7.2.1.0_x86_64.bin", "dest": "" }
    - { "name": "sym-7.2.1.1_x86_64.tar.gz", "dest": "" }
    - { "name": "sym_com_entitlement.dat", "dest": "symphony-entitlement" }
  when: not installdir.stat.exists

- file:
    path: /tmp/sym-7.2.1.0_x86_64.bin
    mode: 0755
  when: not installdir.stat.exists

- shell: IBM_SPECTRUM_SYMPHONY_LICENSE_ACCEPT={{ accept_symphony_license }} EGOCOMPUTEHOST={{ compute_node }} CLUSTERNAME={{ cluster_name }} /tmp/sym-7.2.1.0_x86_64.bin --quiet
  args:
    creates: /opt/ibm/spectrumcomputing

- shell: . /opt/ibm/spectrumcomputing/profile.platform; egosh -V | grep 7.2.1.1 >/dev/null 2>&1
  failed_when: false
  register: patched

- unarchive:
    src: /tmp/sym-7.2.1.1_x86_64.tar.gz
    dest: /tmp
    remote_src: yes
  when: patched.rc != 0

- shell: . /opt/ibm/spectrumcomputing/profile.platform && /tmp/sym-7.2.1.1.sh
  args:
    chdir: /tmp
  when: patched.rc != 0
